name: flutter_fit_utils_vaistudio
description: "A flutter package that contains pre-built utilities for VaiStudio apps. Ranges from extensions, to configs, to providers
and more."
version: ^2.4.2
repository: https://github.com/s0punk/flutter_fit_utils_vaistudio
issue_tracker: https://github.com/s0punk/flutter_fit_utils_vaistudio/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^5.4.1
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_fit_utils: ^2.4.2
  flutter_fit_utils_config: ^1.0.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  intl: ^0.20.2
  go_router: ^14.7.2
  package_info_plus: ^8.1.4
  provider: ^6.1.2
  purchases_flutter: ^8.4.4
  flutter_fit_utils_ui: ^1.6.0
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.2
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.4
  firebase_crashlytics: ^4.3.1
  quick_actions: ^1.1.0
  adaptive_dialog: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/