name: flutter_fit_utils_vaistudio
description: "A flutter package that contains pre-built utilities for VaiStudio apps. Ranges from extensions, to configs, to providers
and more."
version: 1.2.0
repository: https://github.com/s0punk/flutter_fit_utils_vaistudio
issue_tracker: https://github.com/s0punk/flutter_fit_utils_vaistudio/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.2.6
  flutter:
    sdk: flutter
  flutter_fit_utils: ^3.0.0
  flutter_fit_utils_config: ^1.0.3
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1
  intl: ^0.20.2
  go_router: ^15.1.3
  package_info_plus: ^8.3.0
  provider: ^6.1.5
  purchases_flutter: ^8.10.1
  flutter_fit_utils_ui: ^1.7.6
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.4
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6
  firebase_crashlytics: ^4.3.6
  quick_actions: ^1.1.0
  adaptive_dialog: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/