name: flutter_fit_utils_vaistudio
description: "A flutter package that contains pre-built utilities for VaiStudio apps. Ranges from extensions, to configs, to providers
and more."
version: 1.0.0
repository: https://github.com/s0punk/flutter_fit_utils_vaistudio
issue_tracker: https://github.com/s0punk/flutter_fit_utils_vaistudio/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  firebase_auth: ^4.19.6
  firebase_messaging: ^14.9.4
  flutter:
    sdk: flutter
  flutter_fit_utils: ^2.0.0
  flutter_fit_utils_config: ^1.0.0
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  provider: ^6.1.2
  purchases_flutter: ^6.29.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: